aliases:
  dp: deployments
  pd: pods
  ss: statefulsets
  cj: cronjobs
  ds: daemonsets
  cm: configmaps
  sc: v1/secrets
  jb: jobs
  cr: clusterroles
  crb: clusterrolebindings
  rl: roles
  rb: rolebindings
  np: networkpolicies
  pv: persistentvolumes
  pvc: persistentvolumeclaims
