plugins:
  log-less-container:
    shortCut: Shift-L
    description: "logs|less"
    scopes:
      - containers
    command: bash
    background: false
    args:
      - -c
      - '"$@" | less'
      - dummy-arg
      - kubectl
      - logs
      - -c
      - $NAME
      - $POD
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
      - --kubeconfig
      - $KUBECONFIG
  scale-restart:
    shortCut: Shift-R
    confirm: true
    description: scale-restart
    scopes:
      - deploy
    command: sh
    background: false
    args:
      - -c
      - "helm get values $COL-NAME -n $NAMESPACE --kube-context $CONTEXT | less -K"
  helm-values:
    shortCut: v
    confirm: false
    description: Values
    scopes:
      - helm
    command: sh
    background: false
    args:
      - -c
      - "helm get values $COL-NAME -n $NAMESPACE --kube-context $CONTEXT | less -K"
  watch-events:
    shortCut: Shift-E
    confirm: false
    description: Get Events
    scopes:
      - all
    command: sh
    background: false
    args:
      - -c
      - "watch -n 5 kubectl get events --context $CONTEXT --namespace $NAMESPACE --field-selector involvedObject.name=$NAME"